version: "3.7"

services:
  calculator:
    build: ./calculator
    volumes:
      - ./calculator:/app

  get-lorem:
    build: ./get-lorem
    volumes:
      - ./get-lorem:/app

  web:
    build: ./web

    volumes:
      - ./web/src:/app/src
    ports:
      - 3000:3000

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web
      - calculator
      - get-lorem
